### ISSUE TITLE
Memory protection violation (memory dump) on the prev/next button click

### ISSUE THREAD

**Issue by nwg-piotr** [jovanlanik/gtklock-playerctl-module#1]
Home, sweet home, at last. I'm back on my main machine, trying your latest releases. Installed all packages from scratch, and I still see the same memory dump.

**Also**: when I focus another output, playerctl appears on it, but disappears forever when I focus the previous display back again.

~~**Also**: `--art-size` and `--position`  arguments seem to take no affect.~~ (edit: it works)

**Comment by jovanlanik** [comment]
> Home, sweet home, at last. I'm back on my main machine, trying your latest releases. Installed all packages from scratch, and I still see the same memory dump.

Can't replicate, can you send me a backtrace?
> **Also**: when I focus another output, playerctl appears on it, but disappears forever when I focus the previous display back again.

Can replicate, working on a fix.

**Comment by nwg-piotr** [comment]
> Can't replicate, can you send me a backtrace?

How do I do it?

**Comment by jovanlanik** [comment]
Install gdb, then run `$ gdb gtklock --args -- -m playerctl-module`.
In gdb run `(gdb) start` and `(gdb) cont`. gtklock should open.
When you crash it, run `(gdb) bt` and send me the output.
You can exit by running `(gdb) quit`.

**Comment by nwg-piotr** [comment]
Are you sure you typed everything ok? I don't know this tool.

```text
]$ LC_ALL=C gdb gtklock --args -- -m playerctl-module
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
--: No such file or directory.
(gdb) start
No symbol table loaded.  Use the "file" command.
(gdb) 
```

**Comment by jovanlanik** [comment]
My bad. Try `$ gdb --args gtklock -- -m playerctl-module`

**Comment by nwg-piotr** [comment]
Well, it didn't start fro me:

```text
$ gdb --args gtklock -- -m playerctl-module
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from gtklock...
(No debugging symbols found in gtklock)
(gdb) start
Temporary breakpoint 1 at 0x5020
Starting program: /usr/bin/gtklock -- -m playerctl-module
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Temporary breakpoint 1, 0x0000555555559020 in main ()
(gdb) cont
Continuing.
[New Thread 0x7ffff2fff6c0 (LWP 315993)]
[New Thread 0x7ffff27fe6c0 (LWP 315994)]
[New Thread 0x7ffff1ffd6c0 (LWP 315998)]
[New Thread 0x7ffff17fc6c0 (LWP 316000)]

(gtklock:315651): GLib-GIO-CRITICAL **: 17:29:56.931: This application can not open files.

Thread 1 "gtklock" received signal SIGSEGV, Segmentation fault.
0x00007ffff7f7c58d in wl_proxy_destroy () from /usr/lib/libwayland-client.so.0
(gdb) cont
Continuing.
Couldn't get registers: Nie ma takiego procesu.
(gdb) [Thread 0x7ffff17fc6c0 (LWP 316000) exited]
[Thread 0x7ffff1ffd6c0 (LWP 315998) exited]
[Thread 0x7ffff2fff6c0 (LWP 315993) exited]
[Thread 0x7ffff577a980 (LWP 315651) exited]
[Thread 0x7ffff27fe6c0 (LWP 315994) exited]
[New process 315651]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.

(gdb) bt
No stack.
```

**Comment by nwg-piotr** [comment]
I also tried on my testing lappy, which has a fresh Arch+nwg-shell installation. The playerctl module crashes here as well.

**Comment by nwg-piotr** [comment]
One way or another, my code is ready to support all the 3 modules. The part that supports the playerctl module has been turned off temporarily.

**Comment by nwg-piotr** [comment]
> Can't replicate, can you send me a backtrace?

Hint: it happens to me on Google Chrome & Chromium, and does not on Firefox & Audacious.

**Comment by jovanlanik** [comment]
I don't think the first message has anything to do with it but it's still a bug so I fixed it in master.
I'll try testing with chrome...

**Comment by nwg-piotr** [comment]
Fingers crossed. ;)

**Comment by jovanlanik** [comment]
Can you try out the newest release? It's up on the AUR.

**Comment by nwg-piotr** [comment]
It does not crash any longer, congrats! However, there's one more issue. I'll report in a minute.
