### ISSUE TITLE
[1.4.0] album cover and Play/Pause button don't refresh

### ISSUE THREAD

**Issue by nwg-piotr** [jovanlanik/gtklock-playerctl-module#2]
1. After changing a tune with the Next / Previous button, the once loaded album image remains the same. Tested with Firefox (local `artUrl`) and Epiphany (remote `artUrl`). **[edit]** The picture remains unchanged per display. I have album covers on 2 of 3 displays, and always the notes icon on the third one.

3. The Play / Pause button does not reflect the current playerctl status. It always remains in the same state as when the screen got locked.

**Comment by jovanlanik** [comment]
Hopefully fixed in master.

**Comment by nwg-piotr** [comment]
I'll check tonight. Thanks!

**Comment by nwg-piotr** [comment]
It works well on Firefox. On Epiphany, however (remote images), pressing the next/previous button displays the placeholder notes icon.

**Comment by h4-n1** [comment]
This is also an issue on 2.0.1 with Spotify (AUR version). The play/pause button works, but the album cover is never updated when changing the track using the buttons or through other means. Is there any way I could help debug this?

**Comment by nwg-piotr** [comment]
Possibly it has something to do with Spotify itself. I didn't dig into it much, but take a look at this: https://github.com/nwg-piotr/nwg-panel/issues/172

**Comment by jovanlanik** [comment]
> This is also an issue on 2.0.1 with Spotify (AUR version). The play/pause button works, but the album cover is never updated when changing the track using the buttons or through other means. Is there any way I could help debug this?

Is no cover loaded at all or loads at first and doesn't update?

**Comment by jovanlanik** [comment]
Also I think it would be best if you opened another issue for this @h4-n1

**Comment by nwg-piotr** [comment]
Seems to be no longer an issue in v2.0.0.
