### ISSUE TITLE
[feature request] Could the playerctl window remain still visible?

### ISSUE THREAD

**Issue by nwg-piotr** [jovanlanik/gtklock-playerctl-module#3]
Title.

**Comment by jovanlanik** [comment]
By this you mean visible on unfocused outputs?

**Comment by nwg-piotr** [comment]
...as well as when started with `--start-hidden` or when `--idle-time` expires.

**Comment by jovanlanik** [comment]
Added --show-hidden option

**Comment by nwg-piotr** [comment]
Works perfectly well. Many thanks!

**Comment by nwg-piotr** [comment]
So, it looks like this now (and I like it):

![2022-10-01-014111_screenshot](https://user-images.githubusercontent.com/20579136/193369718-e150ce56-8422-48da-b5b5-d3f1b980464f.png)

![2022-10-01-014121_screenshot](https://user-images.githubusercontent.com/20579136/193369725-a4a67af3-df92-44d2-83e4-389f48b137e8.png)

**Comment by nwg-piotr** [comment]
OK, I'm ready with nwg-shell 0.3.4 and nwg-shell-config 0.3.15. I may publish them as soon as gtklock-playerctl-module with the `--show-hidden` argument support is packaged.

**Comment by jovanlanik** [comment]
Done, sorry for the delay.

**Comment by nwg-piotr** [comment]
No problem. We work on the OSS stuff when we have time. Thank you!
