### ISSUE TITLE
v2.0.0 constant memory dump

### ISSUE THREAD

**Issue by nwg-piotr** [jovanlanik/gtklock-playerctl-module#5]
I can't get the new version to work. Crashes regardless of the circumstances, with or without a player working.

```text
$ gtklock -m /usr/lib/gtklock/playerctl-module.so

(gtklock:53071): GLib-CRITICAL **: 03:11:33.120: g_key_file_load_from_file: assertion 'file != NULL' failed
Naruszenie ochrony pamięci (zrzut pamięci)

$ gtklock -m playerctl-module

(gtklock:53356): GLib-CRITICAL **: 03:11:41.839: g_key_file_load_from_file: assertion 'file != NULL' failed
Naruszenie ochrony pamięci (zrzut pamięci)
```

**Comment by jovanlanik** [comment]
As always, thank you for the report. Seems this issue appears only then there isn't a config file, so I missed it.
Will push out a fixed release.

**Comment by nwg-piotr** [comment]
Thank you! Thanks to this, I will be able to release nwg-shell-config tonight.

**Comment by jovanlanik** [comment]
I also want to try fixing #4 before I release...

**Comment by nwg-piotr** [comment]
> I also want to try fixing #4 before I release...

When done, I'll be able to remove the workaround from my code.

**Comment by nwg-piotr** [comment]
Confirmed to work like a charm. Thanks!
