### ISSUE TITLE
Album cover issues

### ISSUE THREAD

**Issue by System64fumo** [jovanlanik/gtklock-playerctl-module#7]
Since https://github.com/jovanlanik/gtklock-playerctl-module/issues/2 was closed i thought it would be appropriate to start a new issue.

The issue above (Album cover not updating) is still an issue at least for me

I've also noticed that it crashes if an album file is gone
Example:
Open firefox, watch a video on youtube, close the tab, crash
```
** (gtklock:29791): WARNING **: 14:04:20.812: Failed loading album art: Error opening file /home/amir/.mozilla/firefox/firefox-mpris/25560_2.png: No such file or directory
Segmentation fault
```

It also crashes when using spotube (Whenever the next song starts playing)
```
GLib:ERROR:../glib/glib/gvariant-serialiser.c:1551:g_variant_serialised_n_children: code should not be reached
Bail out! GLib:ERROR:../glib/glib/gvariant-serialiser.c:1551:g_variant_serialised_n_children: code should not be reached
Aborted
```

**Comment by jovanlanik** [comment]
I successfully replicated the first issue on my system.

**Comment by jovanlanik** [comment]
Can you try the latest master?

**Comment by System64fumo** [comment]
Can't really use gtklock on hyprland..

**Comment by jovanlanik** [comment]
Oh, I'm sorry to hear that. I've fixed some bugs on hyprland recently, the next release should work well.

**Comment by System64fumo** [comment]
Awesome! Though i kinda stopped using lockscreens altogether on my devices..

**Comment by jovanlanik** [comment]
Okay, I'll consider this issue closed if I can't replicate it again.
