### ISSUE TITLE
Port to libsoup3

### ISSUE THREAD

**Issue by Maytha8** [jovanlanik/gtklock-playerctl-module#9]
libsoup3 should be used in favor of the older libsoup2.4.
libsoup3 was released in late 2021. This is a major API bump from libsoup2.4.
[Info on migrating from libsoup2.4 to libsoup3](https://libsoup.org/libsoup-3.0/migrating-from-libsoup-2.html)

Forwarded from [Debian#1073948](https://bugs.debian.org/1073948)

Thanks,
Maytham

**Comment by jovanlanik** [comment]
I ported to libsoup3 in master and will be testing for a few days. If I have no issues I will push a release.

**Comment by jovanlanik** [comment]
Seems to work fine.
